/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Frame(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/frame.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.node6.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

useGLTF.preload('/frame.glb')
